language: ruby
services:
  - postgresql
gemfile:
  - Gemfile.sequel4
  - Gemfile.sequel5
rvm:
  - 2.2.7
  - 2.3.3
  - 2.4.1
before_script:
  - psql -c 'create database sequel_test;' -U postgres
before_install: gem install bundler -v 1.10.5
